# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np

arr = np.random.random([3,3,3])
print(arr)

[[[0.99301762 0.91901849 0.7133821 ]
  [0.88008405 0.95346517 0.20406779]
  [0.32441166 0.62417315 0.7812965 ]]

 [[0.50386783 0.54891262 0.36124841]
  [0.35740156 0.09950078 0.85499028]
  [0.35508708 0.2900899  0.16070478]]

 [[0.52111481 0.59287836 0.41920991]
  [0.84704114 0.68253357 0.1432892 ]
  [0.51070173 0.45908152 0.05518638]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
c = np.diag(1+np.arange(4),-1)
c

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
a = np.zeros((8,8))
# a[1::2,::2]=1
a[::2,1::2]=1
a[1::2,::2]=1
a
    

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 4. Normalize a 5x5 random matrix

In [4]:
z= np.random.random((5,5))
Zmax,Zmin= z.max(),z.min()
z= (z-Zmin)/(Zmax-Zmin)
print(z)


[[0.43757981 0.91757584 0.7768728  0.         0.50143059]
 [0.72632846 0.54661464 0.17065901 0.86249053 0.64471285]
 [0.43503883 0.09496619 0.94530374 0.96267645 0.92458375]
 [0.92351907 0.64403296 0.14761899 0.96239671 0.63483633]
 [0.10233384 0.35334707 0.1799028  0.87981511 1.        ]]


# 5.  How to find common values between two arrays?

In [5]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2],[7,3]])
np.intersect1d(arr1,arr2)

array([1, 2, 3])

# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yesterday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [7]:
arr3  = np.random.random([3,3])
arr4 = np.random.random([3,3])
equal = np.allclose(arr3,arr4)
print(equal)

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
v = np.random.random(10)
v[v.argmax()] = 0
print(v)

[0.91625818 0.         0.3298906  0.84752263 0.27523134 0.32390707
 0.18387567 0.25396393 0.45925929 0.25365541]


# 9. How to print all the values of an array?

In [9]:
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [10]:
arr5 = np.random.random([3,3])
print(arr5)
t=0
x=0
for i in range(len(arr5)):
    t = arr[i,:].mean()
    arr5[i,:] =arr5[i,:]-t

    
arr5

[[0.17111562 0.66633367 0.1340139 ]
 [0.89894409 0.83241994 0.03891448]
 [0.44581105 0.44537418 0.95138671]]


array([[-0.53920844, -0.04399039, -0.57631016],
       [ 0.50652151,  0.43999736, -0.35350811],
       [-0.02430413, -0.024741  ,  0.48127153]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [11]:
Z = np.array([1,2,3,4,5,6,7,8,9,10])
print(Z)
I = np.random.randint(0,len(Z),20)
print(I)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[ 1  2  3  4  5  6  7  8  9 10]
[7 1 0 7 4 6 9 8 4 8 8 2 4 7 8 5 1 0 6 6]
[ 3  4  4  4  8  7 10 11 13 11]


# 12.How to get the diagonal of a dot product?

In [12]:
arr6 = np.random.randint(0,10,(3,3))
arr7 = np.random.randint(0,10,(3,3))
np.diag(np.dot(arr6,arr7))

array([85, 30, 54])

# 13.How to find the most frequent value in an array?

In [13]:
arr8 = np.random.randint(0,10,10)
print(arr8)
np.bincount(arr8).argmax()

[1 9 4 9 1 8 8 6 3 1]


1

# 14.How to get the n largest values of an array

In [28]:
import numpy as np
x = np.random.randint(1,10,10)
print("Original array:",x)

n = 1
print("n:",n)
print (x[np.argsort(x)[-n:]])

Original array: [1 4 6 8 5 3 6 9 3 6]
n: 1
[9]


# 15.How to create a record array from a regular array?

In [18]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3])
result

rec.array([(1, 'Red', 12.2), (2, 'Green', 15. ), (3, 'White', 20. ),
           (4, 'Orange', 40. )],
          dtype=[('f0', '<i4'), ('f1', '<U6'), ('f2', '<f8')])